name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux_make_check:
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      matrix:
        compiler: [gcc-9, gcc-10, gcc-11, gcc-12, gcc-13, clang-11, clang-12, clang-13, clang-14, clang-15, clang-16, clang-17]
        scheduler: [nemesis, sherwood]
        topology: [hwloc, binders, no]
    env:
      CC: ${{ matrix.compiler }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.compiler == 'gcc-13' }}
      run: sudo apt-add-repository 'ppa:ubuntu-toolchain-r/test' && break || sleep 1
    - if: ${{ matrix.compiler == 'clang-16' }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && break || sleep 1
        sudo apt-add-repository 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main' && break || sleep 1
    - if: ${{ matrix.compiler == 'clang-17' }}
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && break || sleep 1
        sudo apt-add-repository 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main' && break || sleep 1
    - name: install compiler
      run: sudo apt-get install ${{ matrix.compiler }}
    - name: install hwloc
      run: |
        sudo apt-get install hwloc libhwloc-dev
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure --enable-picky --with-scheduler=${{ matrix.scheduler }} --with-topology=${{ matrix.topology }}
        make -j2
    - name: make check
      run: |
        timeout --foreground 3m make check

  mac_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: |
        brew install autoconf automake libtool coreutils # coreutils is to get gtimeout for CI and is not universally required by qthreads.
    - name: install hwloc
      run: |
        brew install hwloc
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure --enable-picky
        make -j3
## Currently hangs on OSX -- https://github.com/Qthreads/qthreads/issues/59
    - name: make check
      run: |
        gtimeout --foreground 8m make check

  sanitizers:
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      matrix:
        sanitizer: [address, memory, thread, undefined]
        scheduler: [nemesis, sherwood]
        topology: [hwloc, binders, no]
    env:
      CC: clang-17
      CFLAGS: "-fsanitize=${{ matrix.sanitizer }}"
      LDFLAGS: "-fsanitize=${{ matrix.sanitizer }}"
    steps:
    - uses: actions/checkout@v3
    - name: install compiler
      run: |
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - && break || sleep 1
        sudo apt-add-repository 'deb https://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main' && break || sleep 1
        sudo apt-get install clang-17
    - name: install hwloc
      run: |
        sudo apt-get install hwloc libhwloc-dev
        hwloc-ls --version
    - name: build qthreads
      run: |
        ./autogen.sh
        ./configure --enable-picky --with-scheduler=${{ matrix.scheduler }} --with-topology=${{ matrix.topology }}
        make -j2
    - name: make check
      run: |
        timeout --foreground 6m make check
